language: erlang
otp_release:
  - 17.0
notifications:
  recipients:
    - adam@apathydrive.com
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.2/Precompiled.zip
  - unzip -d elixir Precompiled.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test
after_success:
  - "mix compile && mix coveralls.travis"
env:
  - MIX_ENV=test
